sudo: enabled
dist: trusty

script:
        - bash 20170605.sh
env:
        - worker=1
        - worker=2
        - worker=3
        - worker=4
        - worker=5
        - worker=6
        - worker=7
        - worker=8
        - worker=9
        - worker=10
        - worker=11
        - worker=12
        - worker=13
        - worker=14
        - worker=15
        - worker=16
        - worker=17
        - worker=18
        - worker=19
        - worker=20
        - worker=21
        - worker=22
        - worker=23
        - worker=24
        - worker=25
        - worker=26
        - worker=27
        - worker=28
        - worker=29
        - worker=30
        - worker=31
        - worker=32
        - worker=33
        - worker=34
        - worker=35
        - worker=36
        - worker=37
        - worker=38
        - worker=39
        - worker=40
        - worker=41
        - worker=42
        - worker=43
        - worker=44
        - worker=45
        - worker=46
        - worker=47
        - worker=48
        - worker=49
        - worker=50
        - worker=51
        - worker=52
        - worker=53
        - worker=54
        - worker=55
        - worker=56
        - worker=57
        - worker=58
        - worker=59
        - worker=60
        - worker=61
        - worker=62
        - worker=63
        - worker=64
        - worker=65
        - worker=66
        - worker=67
        - worker=68
        - worker=69
        - worker=70
        - worker=71
        - worker=72
        - worker=73
        - worker=74
        - worker=75
        - worker=76
        - worker=77
        - worker=78
        - worker=79
        - worker=80
        - worker=81
        - worker=82
        - worker=83
        - worker=84
        - worker=85
        - worker=86
        - worker=87
        - worker=88
        - worker=89
        - worker=90
        - worker=91
        - worker=92
        - worker=93
        - worker=94
        - worker=95
        - worker=96
        - worker=97
        - worker=98
        - worker=99
        - worker=100
        - worker=101
        - worker=102
        - worker=103
        - worker=104
        - worker=105
        - worker=106
        - worker=107
        - worker=108
        - worker=109
        - worker=110
        - worker=111
        - worker=112
        - worker=113
        - worker=114
        - worker=115
        - worker=116
        - worker=117
        - worker=118
        - worker=119
        - worker=120
        - worker=121
        - worker=122
        - worker=123
        - worker=124
        - worker=125
        - worker=126
        - worker=127
        - worker=128
        - worker=129
        - worker=130
        - worker=131
        - worker=132
        - worker=133
        - worker=134
        - worker=135
        - worker=136
        - worker=137
        - worker=138
        - worker=139
        - worker=140
        - worker=141
        - worker=142
        - worker=143
        - worker=144
        - worker=145
        - worker=146
        - worker=147
        - worker=148
        - worker=149
        - worker=150
        - worker=151
        - worker=152
        - worker=153
        - worker=154
        - worker=155
        - worker=156
        - worker=157
        - worker=158
        - worker=159
        - worker=160
        - worker=161
        - worker=162
        - worker=163
        - worker=164
        - worker=165
        - worker=166
        - worker=167
        - worker=168
        - worker=169
        - worker=170
        - worker=171
        - worker=172
        - worker=173
        - worker=174
        - worker=175
        - worker=176
        - worker=177
        - worker=178
        - worker=179
        - worker=180
        - worker=181
        - worker=182
        - worker=183
        - worker=184
        - worker=185
        - worker=186
        - worker=187
        - worker=188
        - worker=189
        - worker=190
        - worker=191
        - worker=192
        - worker=193
        - worker=194
        - worker=195
        - worker=196
        - worker=197
        - worker=198
        - worker=199
        - worker=200
